#!/usr/bin/env bash
# abort on error, undefined variables
set -eu
# print commands before execution
set -x

# configuration
BUILD_CONFIG="Release"
BUILD_OUTPUT_DIR=$(realpath "out$BUILD_CONFIG")
BUILD_NATIVELIBRARY_BUILD_DIR=$(realpath NativeLibrary/cmake-build-release)

# remove output folder
(rm -r $BUILD_OUTPUT_DIR || true)
mkdir $BUILD_OUTPUT_DIR

# build CSharpApp
dotnet publish CSharpApp -c $BUILD_CONFIG -o $BUILD_OUTPUT_DIR

# build NativeLibrary
mkdir -p $BUILD_NATIVELIBRARY_BUILD_DIR
cd $BUILD_NATIVELIBRARY_BUILD_DIR
    # generate build scripts
    cmake ..     

    # build using all cores
    cmake --build . --config $BUILD_CONFIG -j $(nproc)
    
    cp -f libNativeLibrary.so $BUILD_OUTPUT_DIR

