#!/usr/bin/env bash
# abort on error, undefined variables
set -eu
# print commands before execution
set -x

# configuration
BUILD_CONFIG="Debug"
if [ $# -eq 1 ]; then
    BUILD_CONFIG=$1
fi
BASEDIR=$(dirname $0)
BUILD_OUTPUT_DIR="$BASEDIR/out/$BUILD_CONFIG"
NATIVELIBRARY_DIR="${BASEDIR}/NativeLibrary"
BUILD_NATIVELIBRARY_BUILD_DIR="${NATIVELIBRARY_DIR}/bin/$BUILD_CONFIG"

# remove output folder
(rm -r $BUILD_OUTPUT_DIR || true)
mkdir -p $BUILD_OUTPUT_DIR

# build CSharpApp
dotnet publish CSharpApp -c $BUILD_CONFIG -o $BUILD_OUTPUT_DIR

# build NativeLibrary
mkdir -p $BUILD_NATIVELIBRARY_BUILD_DIR
cd $BUILD_NATIVELIBRARY_BUILD_DIR
    # generate build scripts
    cmake $NATIVELIBRARY_DIR   

    # build using all cores
    cmake --build . --config $BUILD_CONFIG -j $(nproc)
    
    cp -f libNativeLibrary.so $BUILD_OUTPUT_DIR

